--一.客户对帐表
--1.查询客户对帐头信息
SELECT 
M1.NAME,
M1.ADDRESS,
M1.LAST_TEL_NO,
M1.LAST_LINK_MAN,
T1.CUSTOMER_ID,
T1.制作次数,
T1.消费金额,
T1.总计欠款
FROM
(
	SELECT 
	CUSTOMER_ID,
	COUNT(*) AS 制作次数,
	ISNULL(SUM(SUM_AMOUNT),0) AS 消费金额,
	ISNULL(SUM(REAL_PAID_AMOUNT-PAID_AMOUNT),0) AS 总计欠款 
	FROM ORDERS 
	WHERE CUSTOMER_ID=15549
	AND MEMBER_CARD_ID<>2232
	GROUP BY CUSTOMER_ID
) T1
LEFT JOIN CUSTOMER M1
ON T1.CUSTOMER_ID=M1.ID

--2.查询客户对帐Detail信息
SELECT T1.*,ISNULL(T2.抹零,0) AS 抹零,ISNULL(T2.优惠,0) AS 优惠 
FROM 
(
	SELECT ID,BALANCE_DATE_TIME,SUM_AMOUNT AS 总额,REAL_PAID_AMOUNT-PAID_AMOUNT AS 挂帐欠款,REAL_PAID_AMOUNT AS 实收金额
	FROM ORDERS 
	WHERE CUSTOMER_ID=15549
	AND MEMBER_CARD_ID<>2232
) T1
LEFT JOIN 
(
	--抹零,优惠取得
	SELECT T.ID,MAX(T.抹零) AS 抹零,MAX(T.优惠) AS 优惠 FROM 
	(
		SELECT 
		T1.ID,
		CASE WHEN T4.CONCESSION_TYPE=1 THEN ISNULL(SUM(T4.CONCESSION_AMOUNT),0) END AS 抹零,
		CASE WHEN T4.CONCESSION_TYPE=2 THEN ISNULL(SUM(T4.CONCESSION_AMOUNT),0) END AS 优惠
		FROM
		(
			SELECT 
			ID,
			BALANCE_DATE_TIME,
			SUM_AMOUNT
			FROM ORDERS
			WHERE CUSTOMER_ID=15549
			AND MEMBER_CARD_ID<>2232
		) T1
	LEFT JOIN GATHERING_ORDERS T2
	ON T1.ID=T2.ORDERS_ID
	LEFT JOIN GATHERING T3
	ON T2.GATHERING_ID =T3.ID
	LEFT JOIN PAYMENT_CONCESSION T4
	ON T3.ID=T4.GATHERING_ID
	GROUP BY T1.ID,T4.CONCESSION_TYPE
	) T
	GROUP BY T.ID
) T2
ON T1.ID=T2.ID
ORDER BY T1.ID


--二.异常价格加工单汇总
SELECT T1.*,ISNULL(T2.抹零,0) AS 抹零,ISNULL(T2.优惠,0) AS 优惠,ISNULL(T2.折让,0) AS 折让
FROM	(
	--  取得工单号,客户名称,总额,应收,实收,收银,备注 	
	SELECT
	T1.ID,
	T1.CUSTOMER_NAME,
	T1.SUM_AMOUNT AS 总额,
	T1.REAL_PAID_AMOUNT AS 应收,
	T1.REAL_PAID_AMOUNT AS 实收,
	T2.NAME,
	T1.UPDATE_DATE_TIME,
	T1.MEMO
	FROM ORDERS T1
	LEFT JOIN EMPLOYEE T2
	ON T1.UPDATE_USER=T2.ID
	--工单状态未已完成
	WHERE T1.STATUS=5
	)T1
LEFT JOIN
	(
		--抹零,优惠,折让取得
		SELECT T.ID,MAX(T.抹零) AS 抹零,MAX(T.优惠) AS 优惠,MAX(T.折让) AS 折让 FROM 
		(
			SELECT 
			T1.ID,
			CASE WHEN T4.CONCESSION_TYPE=1 THEN ISNULL(SUM(T4.CONCESSION_AMOUNT),0) END AS 抹零,
			CASE WHEN T4.CONCESSION_TYPE=2 THEN ISNULL(SUM(T4.CONCESSION_AMOUNT),0) END AS 优惠,
			CASE WHEN T4.CONCESSION_TYPE=3 THEN ISNULL(SUM(T4.CONCESSION_AMOUNT),0) END AS 折让
			FROM
			(
				SELECT 
				ID,
				BALANCE_DATE_TIME,
				SUM_AMOUNT
				FROM ORDERS
			) T1
		LEFT JOIN GATHERING_ORDERS T2
		ON T1.ID=T2.ORDERS_ID
		LEFT JOIN GATHERING T3
		ON T2.GATHERING_ID =T3.ID
		LEFT JOIN PAYMENT_CONCESSION T4
		ON T3.ID=T4.GATHERING_ID
		GROUP BY T1.ID,T4.CONCESSION_TYPE
		) T
		GROUP BY T.ID
	)T2
ON T1.ID=T2.ID
WHERE 1=1
AND T1.CUSTOMER_NAME<>'西北设计院'
AND ISNULL(T2.抹零,0)>=0
AND ISNULL(T2.优惠,0)>=0
AND ISNULL(T2.折让,0)>=0
AND T1.UPDATE_DATE_TIME>'2005-01-01'
ORDER BY T1.ID

--三.波动客户查询

--新老客户消费统计

--异常消费会员查询

--会员消费统计





/*
SELECT * FROM ORDERS
select * from workflow.MEMBER_CARD
SELECT M1.ADDRESS,
M1.LAST_TEL_NO,
M1.LAST_LINK_MAN FROM CUSTOMER M1

--付款优惠
SELECT * FROM PAYMENT_CONCESSION

*/
